version: "3.8"

networks:
  btk_test_net:
    name: btk_test_net

services:
  sut:
    build: tests/.
    environment:
      - DEBUG
      - PATTERN
    networks:
      - btk_test_net
    volumes:
      - "${PWD}/tests:/tests:ro"
      - "${PWD}/../tmp:/tmp/insdc-pipeline/run_busco4"

  btk:
    build: .
    networks:
      - btk_test_net


    